// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.starit.janjoonweb.ui.mb.converter;

import com.starit.janjoonweb.ui.mb.converter.JJProfileConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JJProfileConverter_Roo_Configurable {
    
    declare @type: JJProfileConverter: @Configurable;
    
}
