// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.funder.janjoonweb.domain;

import com.funder.janjoonweb.domain.JJBuild;
import com.funder.janjoonweb.domain.JJBuildDataOnDemand;
import com.funder.janjoonweb.domain.JJBuildRepository;
import com.funder.janjoonweb.domain.JJBuildService;
import com.funder.janjoonweb.domain.JJContactDataOnDemand;
import com.funder.janjoonweb.domain.JJVersionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect JJBuildDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JJBuildDataOnDemand: @Component;
    
    private Random JJBuildDataOnDemand.rnd = new SecureRandom();
    
    private List<JJBuild> JJBuildDataOnDemand.data;
    
    @Autowired
    JJContactDataOnDemand JJBuildDataOnDemand.jJContactDataOnDemand;
    
    @Autowired
    JJVersionDataOnDemand JJBuildDataOnDemand.jJVersionDataOnDemand;
    
    @Autowired
    JJBuildService JJBuildDataOnDemand.jJBuildService;
    
    @Autowired
    JJBuildRepository JJBuildDataOnDemand.jJBuildRepository;
    
    public JJBuild JJBuildDataOnDemand.getNewTransientJJBuild(int index) {
        JJBuild obj = new JJBuild();
        setCreationDate(obj, index);
        setDescription(obj, index);
        setEnabled(obj, index);
        setName(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void JJBuildDataOnDemand.setCreationDate(JJBuild obj, int index) {
        Date creationDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationDate(creationDate);
    }
    
    public void JJBuildDataOnDemand.setDescription(JJBuild obj, int index) {
        String description = "description_" + index;
        if (description.length() > 250) {
            description = description.substring(0, 250);
        }
        obj.setDescription(description);
    }
    
    public void JJBuildDataOnDemand.setEnabled(JJBuild obj, int index) {
        Boolean enabled = Boolean.TRUE;
        obj.setEnabled(enabled);
    }
    
    public void JJBuildDataOnDemand.setName(JJBuild obj, int index) {
        String name = "name_" + index;
        if (name.length() > 25) {
            name = name.substring(0, 25);
        }
        obj.setName(name);
    }
    
    public void JJBuildDataOnDemand.setUpdatedDate(JJBuild obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public JJBuild JJBuildDataOnDemand.getSpecificJJBuild(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JJBuild obj = data.get(index);
        Long id = obj.getId();
        return jJBuildService.findJJBuild(id);
    }
    
    public JJBuild JJBuildDataOnDemand.getRandomJJBuild() {
        init();
        JJBuild obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return jJBuildService.findJJBuild(id);
    }
    
    public boolean JJBuildDataOnDemand.modifyJJBuild(JJBuild obj) {
        return false;
    }
    
    public void JJBuildDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = jJBuildService.findJJBuildEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JJBuild' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JJBuild>();
        for (int i = 0; i < 10; i++) {
            JJBuild obj = getNewTransientJJBuild(i);
            try {
                jJBuildService.saveJJBuild(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            jJBuildRepository.flush();
            data.add(obj);
        }
    }
    
}
