// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.funder.janjoonweb.domain;

import com.funder.janjoonweb.domain.JJRequirementDataOnDemand;
import com.funder.janjoonweb.domain.JJRequirementIntegrationTest;
import com.funder.janjoonweb.domain.JJRequirementRepository;
import com.funder.janjoonweb.domain.JJRequirementService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JJRequirementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JJRequirementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JJRequirementIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JJRequirementIntegrationTest: @Transactional;
    
    @Autowired
    private JJRequirementDataOnDemand JJRequirementIntegrationTest.dod;
    
    @Autowired
    JJRequirementService JJRequirementIntegrationTest.jJRequirementService;
    
    @Autowired
    JJRequirementRepository JJRequirementIntegrationTest.jJRequirementRepository;
    
    @Test
    public void JJRequirementIntegrationTest.testCountAllJJRequirements() {
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to initialize correctly", dod.getRandomJJRequirement());
        long count = jJRequirementService.countAllJJRequirements();
        Assert.assertTrue("Counter for 'JJRequirement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JJRequirementIntegrationTest.testFindJJRequirement() {
        JJRequirement obj = dod.getRandomJJRequirement();
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to provide an identifier", id);
        obj = jJRequirementService.findJJRequirement(id);
        Assert.assertNotNull("Find method for 'JJRequirement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JJRequirement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JJRequirementIntegrationTest.testFindAllJJRequirements() {
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to initialize correctly", dod.getRandomJJRequirement());
        long count = jJRequirementService.countAllJJRequirements();
        Assert.assertTrue("Too expensive to perform a find all test for 'JJRequirement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JJRequirement> result = jJRequirementService.findAllJJRequirements();
        Assert.assertNotNull("Find all method for 'JJRequirement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JJRequirement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JJRequirementIntegrationTest.testFindJJRequirementEntries() {
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to initialize correctly", dod.getRandomJJRequirement());
        long count = jJRequirementService.countAllJJRequirements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JJRequirement> result = jJRequirementService.findJJRequirementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JJRequirement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JJRequirement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JJRequirementIntegrationTest.testFlush() {
        JJRequirement obj = dod.getRandomJJRequirement();
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to provide an identifier", id);
        obj = jJRequirementService.findJJRequirement(id);
        Assert.assertNotNull("Find method for 'JJRequirement' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJJRequirement(obj);
        Integer currentVersion = obj.getVersion();
        jJRequirementRepository.flush();
        Assert.assertTrue("Version for 'JJRequirement' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JJRequirementIntegrationTest.testUpdateJJRequirementUpdate() {
        JJRequirement obj = dod.getRandomJJRequirement();
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to provide an identifier", id);
        obj = jJRequirementService.findJJRequirement(id);
        boolean modified =  dod.modifyJJRequirement(obj);
        Integer currentVersion = obj.getVersion();
        JJRequirement merged = (JJRequirement)jJRequirementService.updateJJRequirement(obj);
        jJRequirementRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JJRequirement' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JJRequirementIntegrationTest.testSaveJJRequirement() {
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to initialize correctly", dod.getRandomJJRequirement());
        JJRequirement obj = dod.getNewTransientJJRequirement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JJRequirement' identifier to be null", obj.getId());
        jJRequirementService.saveJJRequirement(obj);
        jJRequirementRepository.flush();
        Assert.assertNotNull("Expected 'JJRequirement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JJRequirementIntegrationTest.testDeleteJJRequirement() {
        JJRequirement obj = dod.getRandomJJRequirement();
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JJRequirement' failed to provide an identifier", id);
        obj = jJRequirementService.findJJRequirement(id);
        jJRequirementService.deleteJJRequirement(obj);
        jJRequirementRepository.flush();
        Assert.assertNull("Failed to remove 'JJRequirement' with identifier '" + id + "'", jJRequirementService.findJJRequirement(id));
    }
    
}
