// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.starit.janjoonweb.ui.mb;

import com.starit.janjoonweb.ui.mb.JJJobBean;
import java.io.Serializable;

privileged aspect JJJobBean_Roo_Serializable{

declare parents:JJJobBean implements Serializable;

private static final long JJJobBean.serialVersionUID=1L;

}
