// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit
// any member(s).

package com.starit.janjoonweb.ui.mb;

import com.starit.janjoonweb.ui.mb.JJProjectBean;
import java.io.Serializable;

privileged aspect JJProjectBean_Roo_Serializable{

declare parents:JJProjectBean implements Serializable;

private static final long JJProjectBean.serialVersionUID=1L;

}
