// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.starit.janjoonweb.ui.mb;

import com.starit.janjoonweb.ui.mb.JJProfileBean;
import java.io.Serializable;

privileged aspect JJProfileBean_Roo_Serializable{

declare parents:JJProfileBean implements Serializable;

private static final long JJProfileBean.serialVersionUID=1L;

}
