// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.starit.janjoonweb.ui.mb;

import com.starit.janjoonweb.ui.mb.JJTaskBean;
import java.io.Serializable;

privileged aspect JJTaskBean_Roo_Serializable {
    
    declare parents: JJTaskBean implements Serializable;
    
    private static final long JJTaskBean.serialVersionUID = 1L;
    
}
