// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.starit.janjoonweb.domain;

import com.starit.janjoonweb.domain.JJCompanyDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JJCompanyDataOnDemand_Roo_Configurable {
    
    declare @type: JJCompanyDataOnDemand: @Configurable;
    
}
